/**
 * 기본 프린터 레이아웃 설정
 * 백오피스에서 설정한 레이아웃을 기본값으로 저장
 */

const defaultPrinterLayoutSettings = {
  "printMode": "graphic",
  "fontFamily": "Arial",
  "headerFontSize": 14,
  "bodyFontSize": 12,
  "footerFontSize": 10,
  "lineSpacing": 12,
  "paperWidth": 80,
  
  // Bill Layout
  "billLayout": {
    "printMode": "graphic",
    "paperWidth": 80,
    "topMargin": 5,
    "leftMargin": 0,
    "fontScale": 2,
    "storeName": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "text": "TheZone Restaurant" },
    "storeAddress": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "text": "123 Main Street, Vancouver, BC" },
    "storePhone": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "solid", "text": "Tel: 778-123-4567" },
    "separator1": { "visible": true, "style": "dotted" },
    "separator2": { "visible": true, "style": "dotted" },
    "separator3": { "visible": true, "style": "dotted" },
    "separator4": { "visible": true, "style": "dotted" },
    "orderNumber": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "orderChannel": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": false, "separatorStyle": "none" },
    "serverName": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": false, "separatorStyle": "none" },
    "dateTime": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": false, "separatorStyle": "dashed" },
    "headerSeparator": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "solid" },
    "items": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "modifiers": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "prefix": ">>" },
    "itemNote": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "prefix": "->", "isItalic": true },
    "itemDiscount": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "isItalic": true },
    "subtotal": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "isItalic": true },
    "discount": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "isItalic": true },
    "taxGST": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "taxPST": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "total": { "fontFamily": "Arial", "fontSize": 9, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "solid" },
    "totalSeparator": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "solid" },
    "greeting": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "text": "Thank you for dining with us!" }
  },

  // Receipt Layout
  "receiptLayout": {
    "printMode": "graphic",
    "paperWidth": 80,
    "topMargin": 5,
    "leftMargin": 0,
    "fontScale": 2,
    "storeName": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "text": "TheZone Restaurant" },
    "storeAddress": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "text": "123 Main Street, Vancouver, BC" },
    "storePhone": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "text": "Tel: 778-123-4567" },
    "separator1": { "visible": true, "style": "dotted" },
    "separator2": { "visible": true, "style": "dotted" },
    "separator3": { "visible": true, "style": "dotted" },
    "separator4": { "visible": true, "style": "dotted" },
    "orderNumber": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "orderChannel": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "serverName": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "dateTime": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "items": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "modifiers": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "prefix": ">>" },
    "itemNote": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "prefix": "->", "isItalic": true },
    "itemDiscount": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "subtotal": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "discount": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "taxGST": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "taxPST": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "total": { "fontFamily": "Arial", "fontSize": 9, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "none" },
    "paymentMethod": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "paymentDetails": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "regular", "visible": true, "separatorStyle": "none" },
    "changeAmount": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "inverse": false },
    "greeting": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "text": "Thank you! Please come again!" },
    "thankYouMessage": { "fontFamily": "Arial", "fontSize": 8, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "text": "*** THANK YOU ***" }
  },

  // Dine-In Kitchen Ticket
  "dineInKitchen": {
    "kitchenPrinter": {
      "enabled": true,
      "printerName": "",
      "printMode": "graphic",
      "paperWidth": 80,
      "topMargin": 10,
      "leftMargin": 0,
      "fontScale": 1,
      "orderType": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 8, "fontWeight": "bold", "visible": false, "separatorStyle": "none", "order": 1, "inverse": true },
      "tableNumber": { "fontFamily": "Arial", "fontSize": 24, "lineSpacing": 8, "fontWeight": "bold", "visible": false, "separatorStyle": "none", "order": 2, "inverse": false },
      "posOrderNumber": { "fontFamily": "Arial", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 3, "inverse": false, "textAlign": "right" },
      "externalOrderNumber": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 4, "inverse": false, "showInHeader": false },
      "guestNumber": { "fontFamily": "Arial", "fontSize": 13, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 5, "inverse": false },
      "separator1": { "visible": true, "style": "dotted" },
      "splitSeparator": { "visible": false, "style": "dashed" },
      "separator2": { "visible": true, "style": "dotted" },
      "serverName": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 6, "inverse": false, "showInHeader": false, "showInFooter": false },
      "dateTime": { "fontFamily": "Arial", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 7, "inverse": false, "showInHeader": false, "showInFooter": true, "textAlign": "right" },
      "items": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 10, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 8, "inverse": false },
      "modifiers": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "prefix": ">>", "order": 9, "inverse": false, "isItalic": true },
      "itemNote": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "prefix": "->", "isItalic": true, "order": 10, "inverse": false },
      "kitchenNote": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 150, "inverse": false, "isItalic": true },
      "paidStatus": { "fontFamily": "Arial", "fontSize": 16, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 11, "inverse": true, "showInHeader": false, "showInFooter": false },
      "specialInstructions": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 200, "inverse": false, "text": "" },
      "mergedElements": [
        { "id": "merge-1769993269777", "leftElement": { "key": "tableNumber", "fontSize": 25, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "rightElement": { "key": "orderType", "fontSize": 25, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": true }, "alignment": "center-center", "verticalAlign": "center", "gap": 25, "order": 1, "lineInverse": true }
      ]
    },
    "waitressPrinter": {
      "enabled": false,
      "printerName": "",
      "printMode": "graphic",
      "paperWidth": 80,
      "topMargin": 5,
      "leftMargin": 0,
      "fontScale": 1,
      "orderType": { "fontFamily": "Arial", "fontSize": 16, "lineSpacing": 8, "fontWeight": "bold", "visible": false, "separatorStyle": "none", "order": 1, "inverse": false },
      "tableNumber": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 8, "fontWeight": "bold", "visible": false, "separatorStyle": "none", "order": 2, "inverse": false },
      "posOrderNumber": { "fontFamily": "Arial", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 3, "inverse": false, "textAlign": "right" },
      "externalOrderNumber": { "fontFamily": "Arial", "fontSize": 10, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 4, "inverse": false, "showInHeader": false },
      "guestNumber": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 5, "inverse": false },
      "separator1": { "visible": true, "style": "dotted" },
      "splitSeparator": { "visible": false, "style": "dashed" },
      "separator2": { "visible": true, "style": "dotted" },
      "serverName": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 6, "inverse": false, "showInHeader": false, "showInFooter": false },
      "dateTime": { "fontFamily": "Arial", "fontSize": 15, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 7, "inverse": false, "showInHeader": false, "showInFooter": true, "textAlign": "right" },
      "items": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 10, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 8, "inverse": false },
      "modifiers": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "prefix": ">>", "order": 9, "inverse": false, "isItalic": true },
      "itemNote": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "prefix": "->", "isItalic": true, "order": 10, "inverse": false },
      "kitchenNote": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 150, "inverse": false },
      "paidStatus": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 11, "inverse": false, "showInHeader": false, "showInFooter": false },
      "specialInstructions": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 200, "inverse": false, "text": "" },
      "mergedElements": [
        { "id": "merge-1769993462870", "leftElement": { "key": "tableNumber", "fontSize": 25, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "rightElement": { "key": "orderType", "fontSize": 25, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "alignment": "center-center", "verticalAlign": "center", "gap": 16, "order": 1, "lineInverse": true }
      ]
    }
  },

  // Take-out (External) Kitchen Ticket
  "externalKitchen": {
    "kitchenPrinter": {
      "enabled": true,
      "printerName": "",
      "printMode": "graphic",
      "paperWidth": 80,
      "topMargin": 10,
      "leftMargin": 0,
      "fontScale": 1,
      "orderType": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 8, "fontWeight": "bold", "visible": false, "separatorStyle": "none", "order": 1, "inverse": true, "showInHeader": true, "showInFooter": false },
      "tableNumber": { "fontFamily": "Arial", "fontSize": 24, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 2, "inverse": false, "showInHeader": false, "showInFooter": false },
      "posOrderNumber": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "regular", "visible": false, "separatorStyle": "none", "order": 3, "inverse": false, "showInHeader": true, "showInFooter": false },
      "externalOrderNumber": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 4, "inverse": true, "showInHeader": false, "showInFooter": false },
      "deliveryChannel": { "fontFamily": "Arial", "fontSize": 18, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 5, "inverse": true, "showInHeader": false, "showInFooter": false },
      "pickupTime": { "fontFamily": "Arial", "fontSize": 24, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 6, "inverse": true, "showInHeader": true, "showInFooter": false },
      "customerName": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": false, "separatorStyle": "none", "order": 7, "inverse": false, "showInHeader": true, "showInFooter": false },
      "customerPhone": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": false, "separatorStyle": "none", "order": 8, "inverse": false, "showInHeader": true, "showInFooter": false },
      "deliveryAddress": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 9, "inverse": false, "showInHeader": false, "showInFooter": false },
      "serverName": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 10, "inverse": false, "showInHeader": false, "showInFooter": false },
      "dateTime": { "fontFamily": "Arial", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 11, "inverse": false, "showInHeader": false, "showInFooter": true, "textAlign": "right" },
      "guestNumber": { "fontFamily": "Arial", "fontSize": 16, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 12, "inverse": true },
      "separator1": { "visible": true, "style": "solid" },
      "splitSeparator": { "visible": false, "style": "dashed" },
      "separator2": { "visible": true, "style": "solid" },
      "items": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 10, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 100, "inverse": false },
      "modifiers": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 5, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "prefix": ">>", "order": 101, "inverse": false, "isItalic": true },
      "itemNote": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 10, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "prefix": "->", "isItalic": true, "order": 102, "inverse": false },
      "kitchenNote": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 150, "inverse": false },
      "paidStatus": { "fontFamily": "Arial", "fontSize": 25, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 13, "inverse": true, "showInHeader": false, "showInFooter": true },
      "specialInstructions": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 200, "inverse": false, "text": "" },
      "mergedElements": [
        { "id": "merge-1769993970575", "leftElement": { "key": "orderType", "fontSize": 25, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": true }, "rightElement": { "key": "posOrderNumber", "fontSize": 25, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "alignment": "center-center", "verticalAlign": "center", "gap": 20, "order": 1, "lineInverse": true },
        { "id": "merge-1769994011052", "leftElement": { "key": "customerPhone", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "rightElement": { "key": "customerName", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "alignment": "center-center", "verticalAlign": "center", "gap": 16, "order": 2 }
      ]
    },
    "waitressPrinter": {
      "enabled": false,
      "printerName": "",
      "printMode": "graphic",
      "paperWidth": 80,
      "topMargin": 5,
      "leftMargin": 0,
      "fontScale": 1,
      "orderType": { "fontFamily": "Arial", "fontSize": 16, "lineSpacing": 8, "fontWeight": "bold", "visible": false, "separatorStyle": "none", "order": 1, "inverse": false, "showInHeader": true, "showInFooter": false },
      "tableNumber": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 2, "inverse": false, "showInHeader": false, "showInFooter": false },
      "posOrderNumber": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": false, "separatorStyle": "none", "order": 3, "inverse": false, "showInHeader": true, "showInFooter": false },
      "externalOrderNumber": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 4, "inverse": false, "showInHeader": false, "showInFooter": false },
      "deliveryChannel": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 5, "inverse": false, "showInHeader": false, "showInFooter": false },
      "pickupTime": { "fontFamily": "Arial", "fontSize": 24, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 6, "inverse": true, "showInHeader": true, "showInFooter": false, "textAlign": "center" },
      "customerName": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": false, "separatorStyle": "none", "order": 7, "inverse": false, "showInHeader": true, "showInFooter": false },
      "customerPhone": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": false, "separatorStyle": "none", "order": 8, "inverse": false, "showInHeader": true, "showInFooter": false },
      "deliveryAddress": { "fontFamily": "Arial", "fontSize": 10, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 9, "inverse": false, "showInHeader": false, "showInFooter": false },
      "serverName": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 10, "inverse": false, "showInHeader": false, "showInFooter": false },
      "dateTime": { "fontFamily": "Arial", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 11, "inverse": false, "showInHeader": false, "showInFooter": true, "textAlign": "right" },
      "guestNumber": { "fontFamily": "Arial", "fontSize": 13, "lineSpacing": 8, "fontWeight": "bold", "visible": false, "separatorStyle": "none", "order": 12, "inverse": false },
      "separator1": { "visible": true, "style": "dashed" },
      "splitSeparator": { "visible": false, "style": "dashed" },
      "separator2": { "visible": true, "style": "dashed" },
      "items": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 10, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 100, "inverse": false },
      "modifiers": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "prefix": ">>", "order": 101, "inverse": false, "isItalic": true },
      "itemNote": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 2, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "prefix": "->", "isItalic": true, "order": 102, "inverse": false },
      "kitchenNote": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 150, "inverse": false },
      "paidStatus": { "fontFamily": "Arial", "fontSize": 24, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 13, "inverse": true, "showInHeader": false, "showInFooter": true, "textAlign": "center" },
      "specialInstructions": { "fontFamily": "Arial", "fontSize": 19, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 200, "inverse": false, "text": "", "showInHeader": true },
      "mergedElements": [
        { "id": "merge-1769993651956", "leftElement": { "key": "orderType", "fontSize": 25, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "rightElement": { "key": "posOrderNumber", "fontSize": 25, "lineSpacing": 8, "fontWeight": "regular", "isItalic": false, "inverse": false }, "alignment": "center-center", "verticalAlign": "center", "gap": 16, "order": 1, "lineInverse": true },
        { "id": "merge-1769993710126", "leftElement": { "key": "customerPhone", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "rightElement": { "key": "customerName", "fontSize": 15, "lineSpacing": 8, "fontWeight": "bold", "isItalic": false, "inverse": false }, "alignment": "center-center", "verticalAlign": "center", "gap": 16, "order": 2 }
      ]
    }
  },

  // Delivery Kitchen Ticket
  "deliveryKitchen": {
    "kitchenPrinter": {
      "enabled": true,
      "printerName": "",
      "printMode": "graphic",
      "paperWidth": 80,
      "topMargin": 10,
      "leftMargin": 0,
      "fontScale": 1,
      "orderType": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 1, "inverse": true, "showInHeader": true, "showInFooter": false },
      "tableNumber": { "fontFamily": "Arial", "fontSize": 24, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 2, "inverse": false, "showInHeader": false, "showInFooter": false },
      "posOrderNumber": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 3, "inverse": false, "showInHeader": true, "showInFooter": false },
      "externalOrderNumber": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 4, "inverse": true, "showInHeader": true, "showInFooter": false },
      "deliveryChannel": { "fontFamily": "Arial", "fontSize": 18, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 5, "inverse": true, "showInHeader": true, "showInFooter": false },
      "pickupTime": { "fontFamily": "Arial", "fontSize": 16, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 6, "inverse": true, "showInHeader": true, "showInFooter": false },
      "customerName": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 7, "inverse": false, "showInHeader": true, "showInFooter": false },
      "customerPhone": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 8, "inverse": false, "showInHeader": true, "showInFooter": false },
      "deliveryAddress": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 9, "inverse": false, "showInHeader": true, "showInFooter": false },
      "serverName": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 10, "inverse": false, "showInHeader": true, "showInFooter": false },
      "dateTime": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 11, "inverse": false, "showInHeader": true, "showInFooter": false },
      "guestNumber": { "fontFamily": "Arial", "fontSize": 16, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 12, "inverse": true },
      "separator1": { "visible": true, "style": "solid" },
      "splitSeparator": { "visible": false, "style": "dashed" },
      "separator2": { "visible": true, "style": "solid" },
      "items": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 100, "inverse": false },
      "modifiers": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "prefix": ">>", "order": 101, "inverse": false },
      "itemNote": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "prefix": "->", "isItalic": true, "order": 102, "inverse": false },
      "kitchenNote": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 150, "inverse": false },
      "paidStatus": { "fontFamily": "Arial", "fontSize": 16, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 13, "inverse": true, "showInHeader": true, "showInFooter": false },
      "specialInstructions": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 200, "inverse": false, "text": "" },
      "mergedElements": []
    },
    "waitressPrinter": {
      "enabled": false,
      "printerName": "",
      "printMode": "graphic",
      "paperWidth": 80,
      "topMargin": 5,
      "leftMargin": 0,
      "fontScale": 1,
      "orderType": { "fontFamily": "Arial", "fontSize": 16, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 1, "inverse": false, "showInHeader": true, "showInFooter": false },
      "tableNumber": { "fontFamily": "Arial", "fontSize": 20, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 2, "inverse": false, "showInHeader": false, "showInFooter": false },
      "posOrderNumber": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 3, "inverse": false, "showInHeader": true, "showInFooter": false },
      "externalOrderNumber": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 4, "inverse": false, "showInHeader": true, "showInFooter": false },
      "deliveryChannel": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 5, "inverse": false, "showInHeader": true, "showInFooter": false },
      "pickupTime": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 6, "inverse": false, "showInHeader": true, "showInFooter": false },
      "customerName": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 7, "inverse": false, "showInHeader": true, "showInFooter": false },
      "customerPhone": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 8, "inverse": false, "showInHeader": true, "showInFooter": false },
      "deliveryAddress": { "fontFamily": "Arial", "fontSize": 10, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 9, "inverse": false, "showInHeader": true, "showInFooter": false },
      "serverName": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 10, "inverse": false, "showInHeader": true, "showInFooter": false },
      "dateTime": { "fontFamily": "Arial", "fontSize": 11, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 11, "inverse": false, "showInHeader": true, "showInFooter": false },
      "guestNumber": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 12, "inverse": false },
      "separator1": { "visible": true, "style": "dashed" },
      "splitSeparator": { "visible": false, "style": "dashed" },
      "separator2": { "visible": true, "style": "dashed" },
      "items": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 100, "inverse": false },
      "modifiers": { "fontFamily": "Arial", "fontSize": 10, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "prefix": ">>", "order": 101, "inverse": false },
      "itemNote": { "fontFamily": "Arial", "fontSize": 10, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "prefix": "->", "isItalic": true, "order": 102, "inverse": false },
      "kitchenNote": { "fontFamily": "Arial", "fontSize": 12, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 150, "inverse": false },
      "paidStatus": { "fontFamily": "Arial", "fontSize": 14, "lineSpacing": 8, "fontWeight": "bold", "visible": true, "separatorStyle": "none", "order": 13, "inverse": false, "showInHeader": true, "showInFooter": false },
      "specialInstructions": { "fontFamily": "Arial", "fontSize": 10, "lineSpacing": 8, "fontWeight": "regular", "visible": true, "separatorStyle": "none", "order": 200, "inverse": false, "text": "" },
      "mergedElements": []
    }
  }
};

module.exports = { defaultPrinterLayoutSettings };
